### PR TITLE
chore(release): v0.68.0-rhobs1

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Review by danielmellado — APPROVED** [review]
overall lgtm, glad that it went smooth

**Comment by simonpasquier** [comment]
Let's see if the rest of the automation runs as smoothly :smile:

**Comment by simonpasquier** [comment]
Hmm it didn't trigger the `create-release` workflow. Maybe I should have used "Rebase and merge" instead of "Create a merge commit"?
From https://github.com/rhobs/obo-prometheus-operator/actions/runs/6480922737/job/17597428889

image

**Comment by danielmellado** [comment]
hmmm weird, let's compare that with a working one (i.e. https://github.com/rhobs/obo-prometheus-operator/pull/33)

**Comment by danielmellado** [comment]
github workflows state that it should check that it starts with 

```
!startsWith(github.event.head_commit.message, 'chore(release):')
```

but I do see that in your commit

**Comment by danielmellado** [comment]
After checking and so, yeah, I think it's probably that case

**Pull request merged**
